"""Trace design/source-art/snuffed-torch.png into the SVG paths the Standings
torches use, written to frontend/src/components/torchPaths.ts.

    cd backend && uv run --with potracer --with pillow --with numpy \\
        python ../design/trace_snuffed_torch.py

The source is Codex's snuffed-torch drawing (an S of smoke rising off an ash
mound with an ember at its crown), one brown plus one orange. Tracing keeps
the shape exactly while letting the component paint it with gradients and
scale it as vector. Re-run after changing the PNG.
"""

from pathlib import Path

import numpy as np
import potrace
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "design" / "source-art" / "snuffed-torch.png"
OUT = ROOT / "frontend" / "src" / "components" / "torchPaths.ts"

UP = 8  # upscale so potrace has smooth edges to follow

im = Image.open(SRC).convert("RGBA")
big = im.resize((im.width * UP, im.height * UP), Image.LANCZOS)
a = np.array(big).astype(int)
opaque = a[..., 3] > 128
r, b = a[..., 0], a[..., 2]
ember = opaque & (r > 140) & (r - b > 70)  # the orange coal
brown = opaque & ~ember


def trace(mask: np.ndarray) -> str:
    """Trace a boolean mask into an SVG path string in source-pixel units."""
    # potracer reads True as white, so invert to trace the shape itself.
    curves = potrace.Bitmap(~mask).trace(
        turdsize=20, alphamax=1.0, opticurve=True, opttolerance=0.3
    )

    def pt(p) -> str:
        return f"{p.x / UP:.2f} {p.y / UP:.2f}"

    parts: list[str] = []
    for curve in curves:
        parts.append(f"M{pt(curve.start_point)}")
        for seg in curve:
            if seg.is_corner:
                parts.append(f"L{pt(seg.c)}L{pt(seg.end_point)}")
            else:
                parts.append(f"C{pt(seg.c1)} {pt(seg.c2)} {pt(seg.end_point)}")
        parts.append("Z")
    return "".join(parts)


ys, xs = np.nonzero(ember)
ember_cx, ember_cy = xs.mean() / UP, ys.mean() / UP
ember_r = max(xs.max() - xs.min(), ys.max() - ys.min()) / UP / 2
widths = brown.sum(axis=1)
mound_top = int(np.argmax(widths > widths.max() * 0.55)) / UP

OUT.write_text(
    f"""// Generated by design/trace_snuffed_torch.py from source-art/snuffed-torch.png
// (do not edit by hand; re-run the script after changing the PNG).
export const SNUFFED = {{
  width: {im.width},
  height: {im.height},
  /** Smoke and ash mound, one shape. */
  smoke: '{trace(brown)}',
  /** The ember at the mound's crown. */
  ember: '{trace(ember)}',
  emberCx: {ember_cx:.2f},
  emberCy: {ember_cy:.2f},
  emberR: {ember_r:.2f},
  /** Top of the ash mound, as a fraction of the height measured up from the bottom. */
  moundFrac: {(im.height - mound_top) / im.height:.2f},
}} as const
"""
)
print(f"wrote {OUT.relative_to(ROOT)}")
